### ISSUE TITLE
Resolved Facts remain highlighted

### ISSUE THREAD

**Issue by dchatters** [youngtai/gedcomx-differ-react#1]
In the old version if a name of a person matched and one or more of the facts matched, the matched facts were not highlighted.  With this version all facts and the names remain highlighted until all facts for that person match.  See attached files.
[008094443_00400.left.edit (1).json](https://github.com/youngtai/gedcomx-differ-react/files/15015639/008094443_00400.left.edit.1.json)
[008094443_00400.right.edit (1).json](https://github.com/youngtai/gedcomx-differ-react/files/15015640/008094443_00400.right.edit.1.json)

**Comment by youngtai** [comment]
@dchatters Yes this is due to the change I made yesterday in how the person to compare against is found. I think we can tweak the logic more to retain the previous behavior you've described so I'll look at doing that.

**Comment by youngtai** [comment]
@dchatters Actually I just pushed a change. Let me know if you see weird things in other situations.
<img width="1857" alt="image" src="https://github.com/youngtai/gedcomx-differ-react/assets/34751242/34435abe-79e9-46fe-8d5a-a32032e595ff">
