### ISSUE TITLE
Record Fields Section requires new tag

### ISSUE THREAD

**Issue by dchatters** [youngtai/gedcomx-differ-react#6]
The record fields section requires the new tag http://familysearch.org/types/fields/SourceCertificateNbr that Randy added last Friday.

Work around is to save one side as the final version.

[004590029_00228.json](https://github.com/user-attachments/files/15526078/004590029_00228.json)
[004590029_00228A.json](https://github.com/user-attachments/files/15526079/004590029_00228A.json)

**Comment by crapo** [comment]
@dchatters , sorry to be a bit dense, but I don't understand the issue. The link doesn't work for me, and I don't understand the work around or why it's needed.

**Comment by dchatters** [comment]
@crapo If you look at the output of GEDCOMX in a text editor you'll see that all the tag names appear in the format of a link, yet they're not links.  On Friday Randy Wilson added a new tag to record the certificate number of a record on an image in the Records Metadata section of GEDCOMX.  The Differ needs to be updated to be able to compare that new tag or add the new tag should one user forget to add it.  
Since, in the differ you can save each file independently, until differ is updated to handle the new tag I will make sure that both files are correct with the exception of the new tag and save that file which has that tag as the final version to be given to the engineers.

**Comment by crapo** [comment]
@dchatters , thanks for the explanation. I mistakenly thought the URI for the tag in your comment was a link to documentation of the new tag. Just to clarify, as described in the GEDCOM X  Conceptual Model Specification (
[https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#uri](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#uri)), Section 1.3.4, "The Uniform Resource Identifier ("URI") is fundamental to the GEDCOM X conceptual model. The URI is used to identify both the data types and data instances. The URI is also used to identify elements of the controlled vocabularies defined by GEDCOM X. The URI is specified by [RFC 3986](http://tools.ietf.org/html/rfc3986)." And, as you say, a URI is not a link (not a URL). What is giving me a little heart burn is that apparently the GEDCOM X spec doesn't include the datatype xs:anyURI, which seems to me to make it impossible to identify external identity and/or location within a GEDCOM-X file.

**Comment by youngtai** [comment]
I just added this and it is live. https://github.com/youngtai/gedcomx-differ-react/commit/b05c47dc804467a46853c9519e5a5ef8647df103
