### ISSUE TITLE
Record Data Section

### ISSUE THREAD

**Issue by dchatters** [youngtai/gedcomx-differ-react#7]
In the two attached files, the left side originally didn't have a Record Data section.  I edited the file in GEDCOMX and entered the metadata information.  However, GEDCOMX put the data at the bottom of the left side while the right side has it at the top.  Differ displays the following error in the Record Data section of the left side:
Source description of unhandled type: undefined
Source description of unhandled type: undefined

Work around is to save the right side as the final version.

[005208754_00029.left.edit.json](https://github.com/user-attachments/files/15748570/005208754_00029.left.edit.json)
[005208754_00029.right.edit.json](https://github.com/user-attachments/files/15748571/005208754_00029.right.edit.json)

**Comment by youngtai** [comment]
I'm not sure why, but the left one is missing a necessary field on a `sourceDescription` for `recordType`: `"resourceType": "http://gedcomx.org/Record",`

So it should look like the right side. Somehow the `sourceDescription` wasn't created correctly in GedcomX Editor/Viewer

I just tried creating a source description and it was created correctly.

**Comment by youngtai** [comment]
FYI @dchatters
